version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            echo ".publish/publish.sh" >> .npmignore
            git clone https://github.com/sequencemedia/publish.git .publish
            .publish/publish.sh "$NPM_TOKEN"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
